name: hledger # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.34' # just for humans, typically '1.2+git' or '1.3.2'
summary: Robust, intuitive plain text accounting # 79 char long summary
description: |
  hledger is lightweight, cross platform, multi-currency, double-entry accounting software. 
  It lets you track money, investments, cryptocurrencies, invoices, time, inventory and more, 
  in a safe, future-proof plain text data format with full version control and privacy.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  hledger:
    command: bin/hledger
    plugs:
    - home
  ui:
    command: bin/hledger-ui
  web:
    command: bin/hledger-web

parts:
  hledger:
    source: https://github.com/simonmichael/hledger
    source-tag: "1.34"
    source-type: git
    plugin: nil
    build-environment:
    - PATH: "/root/.local/bin:$PATH"
    build-packages:
    - curl
    - libgmp-dev
    - libtinfo-dev
    - zlib1g-dev
    override-build: |
      craftctl default
      curl -sSL https://get.haskellstack.org/ | sh
      stack update
      stack build
      stack install --local-bin-path $CRAFT_PART_INSTALL/bin/
